// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: practice/packages/lecture.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mycompany.Mooc {

  /// <summary>Holder for reflection information generated from practice/packages/lecture.proto</summary>
  public static partial class LectureReflection {

    #region Descriptor
    /// <summary>File descriptor for practice/packages/lecture.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LectureReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9wcmFjdGljZS9wYWNrYWdlcy9sZWN0dXJlLnByb3RvEg5teWNvbXBhbnku",
            "bW9vYxodcHJhY3RpY2UvcGFja2FnZXMvdmlkZW8ucHJvdG8aH3ByYWN0aWNl",
            "L3BhY2thZ2VzL2FydGljbGUucHJvdG8ieAoHTGVjdHVyZRIuCgV2aWRlbxgB",
            "IAEoCzIdLm15Y29tcGFueS5tb29jLmNvbnRlbnQuVmlkZW9IABIyCgdhcnRp",
            "Y2xlGAIgASgLMh8ubXljb21wYW55Lm1vb2MuY29udGVudC5BcnRpY2xlSABC",
            "CQoHY29udGVudGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mycompany.Mooc.Content.VideoReflection.Descriptor, global::Mycompany.Mooc.Content.ArticleReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mycompany.Mooc.Lecture), global::Mycompany.Mooc.Lecture.Parser, new[]{ "Video", "Article" }, new[]{ "Content" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Lecture : pb::IMessage<Lecture>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Lecture> _parser = new pb::MessageParser<Lecture>(() => new Lecture());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Lecture> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mycompany.Mooc.LectureReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Lecture() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Lecture(Lecture other) : this() {
      switch (other.ContentCase) {
        case ContentOneofCase.Video:
          Video = other.Video.Clone();
          break;
        case ContentOneofCase.Article:
          Article = other.Article.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Lecture Clone() {
      return new Lecture(this);
    }

    /// <summary>Field number for the "video" field.</summary>
    public const int VideoFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mycompany.Mooc.Content.Video Video {
      get { return contentCase_ == ContentOneofCase.Video ? (global::Mycompany.Mooc.Content.Video) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.Video;
      }
    }

    /// <summary>Field number for the "article" field.</summary>
    public const int ArticleFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mycompany.Mooc.Content.Article Article {
      get { return contentCase_ == ContentOneofCase.Article ? (global::Mycompany.Mooc.Content.Article) content_ : null; }
      set {
        content_ = value;
        contentCase_ = value == null ? ContentOneofCase.None : ContentOneofCase.Article;
      }
    }

    private object content_;
    /// <summary>Enum of possible cases for the "content" oneof.</summary>
    public enum ContentOneofCase {
      None = 0,
      Video = 1,
      Article = 2,
    }
    private ContentOneofCase contentCase_ = ContentOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContentOneofCase ContentCase {
      get { return contentCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearContent() {
      contentCase_ = ContentOneofCase.None;
      content_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Lecture);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Lecture other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Video, other.Video)) return false;
      if (!object.Equals(Article, other.Article)) return false;
      if (ContentCase != other.ContentCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (contentCase_ == ContentOneofCase.Video) hash ^= Video.GetHashCode();
      if (contentCase_ == ContentOneofCase.Article) hash ^= Article.GetHashCode();
      hash ^= (int) contentCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (contentCase_ == ContentOneofCase.Video) {
        output.WriteRawTag(10);
        output.WriteMessage(Video);
      }
      if (contentCase_ == ContentOneofCase.Article) {
        output.WriteRawTag(18);
        output.WriteMessage(Article);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (contentCase_ == ContentOneofCase.Video) {
        output.WriteRawTag(10);
        output.WriteMessage(Video);
      }
      if (contentCase_ == ContentOneofCase.Article) {
        output.WriteRawTag(18);
        output.WriteMessage(Article);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (contentCase_ == ContentOneofCase.Video) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Video);
      }
      if (contentCase_ == ContentOneofCase.Article) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Article);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Lecture other) {
      if (other == null) {
        return;
      }
      switch (other.ContentCase) {
        case ContentOneofCase.Video:
          if (Video == null) {
            Video = new global::Mycompany.Mooc.Content.Video();
          }
          Video.MergeFrom(other.Video);
          break;
        case ContentOneofCase.Article:
          if (Article == null) {
            Article = new global::Mycompany.Mooc.Content.Article();
          }
          Article.MergeFrom(other.Article);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Mycompany.Mooc.Content.Video subBuilder = new global::Mycompany.Mooc.Content.Video();
            if (contentCase_ == ContentOneofCase.Video) {
              subBuilder.MergeFrom(Video);
            }
            input.ReadMessage(subBuilder);
            Video = subBuilder;
            break;
          }
          case 18: {
            global::Mycompany.Mooc.Content.Article subBuilder = new global::Mycompany.Mooc.Content.Article();
            if (contentCase_ == ContentOneofCase.Article) {
              subBuilder.MergeFrom(Article);
            }
            input.ReadMessage(subBuilder);
            Article = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Mycompany.Mooc.Content.Video subBuilder = new global::Mycompany.Mooc.Content.Video();
            if (contentCase_ == ContentOneofCase.Video) {
              subBuilder.MergeFrom(Video);
            }
            input.ReadMessage(subBuilder);
            Video = subBuilder;
            break;
          }
          case 18: {
            global::Mycompany.Mooc.Content.Article subBuilder = new global::Mycompany.Mooc.Content.Article();
            if (contentCase_ == ContentOneofCase.Article) {
              subBuilder.MergeFrom(Article);
            }
            input.ReadMessage(subBuilder);
            Article = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
