// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: practice/packages/videotype.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mycompany.Mooc.Content {

  /// <summary>Holder for reflection information generated from practice/packages/videotype.proto</summary>
  public static partial class VideotypeReflection {

    #region Descriptor
    /// <summary>File descriptor for practice/packages/videotype.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VideotypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFwcmFjdGljZS9wYWNrYWdlcy92aWRlb3R5cGUucHJvdG8SFm15Y29tcGFu",
            "eS5tb29jLmNvbnRlbnQqLgoJVmlkZW9UeXBlEg8KC1VOU1BFQ0lGSUVEEAAS",
            "BwoDTVA0EAESBwoDTU9WEAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Mycompany.Mooc.Content.VideoType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum VideoType {
    [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("MP4")] Mp4 = 1,
    [pbr::OriginalName("MOV")] Mov = 2,
  }

  #endregion

}

#endregion Designer generated code
