# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: 05/main.proto
# Protobuf Python Version: 6.33.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '-rc2',
    '05/main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\r05/main.proto\"L\n\x06\x43ourse\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x18\n\x07\x41uthors\x18\x02 \x03(\x0b\x32\x07.Author\x12\x1a\n\x08Lectures\x18\x03 \x03(\x0b\x32\x08.Lecture\"\x08\n\x06\x41uthor\"J\n\x07Lecture\x12\x17\n\x05Video\x18\x01 \x01(\x0b\x32\x06.VideoH\x00\x12\x1b\n\x07\x41rticle\x18\x02 \x01(\x0b\x32\x08.ArticleH\x00\x42\t\n\x07\x43ontent\"!\n\x05Video\x12\x18\n\x04type\x18\x01 \x01(\x0e\x32\n.VideoType\"\x17\n\x07\x41rticle\x12\x0c\n\x04text\x18\x01 \x01(\t*.\n\tVideoType\x12\x0f\n\x0bUNSUPPORTED\x10\x00\x12\x07\n\x03MP4\x10\x01\x12\x07\n\x03MOV\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, '05.main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOTYPE']._serialized_start=241
  _globals['_VIDEOTYPE']._serialized_end=287
  _globals['_COURSE']._serialized_start=17
  _globals['_COURSE']._serialized_end=93
  _globals['_AUTHOR']._serialized_start=95
  _globals['_AUTHOR']._serialized_end=103
  _globals['_LECTURE']._serialized_start=105
  _globals['_LECTURE']._serialized_end=179
  _globals['_VIDEO']._serialized_start=181
  _globals['_VIDEO']._serialized_end=214
  _globals['_ARTICLE']._serialized_start=216
  _globals['_ARTICLE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
